name: Deploy docker image
on: [push]
jobs:
  push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - name: Docker Build Tag Publish
        uses: bitovi/github-actions-docker-publish@v1.0.7
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
